### ISSUE TITLE
我有几个问题要问一下

### ISSUE THREAD

**Issue by dequinns** [BruceDone/Tiktok#3]
1.tiktok的定时调度用了那个库编写的
2.你搞个中文的说明啊
3.最近的更新，有没有将login和send email这些加上去

**Comment by BruceDone** [comment]
Hi Dequinns:
   首先感谢你的关注
## 哪个库
底层使用的 使用的 croniter，主要是下次执行时间，结合subprocess 

## 中文说明
本框架移植了别人的部分，还有很多不完善的部分，如果有计划大改的话，我会考虑重构一个出来的

## 新的功能
参考楼上的说明

thanks:)
